Feature/fe be/update motorcycle card
ArtemVolok/sales-motorbike-project pull request #33
Opened 2024-03-21 21:14 UTC by ArtemVolok

[FE] add opportunity update motorcycle card, add redirect to admin page after success create and update motorcycle card, small fix in logi and style
[BE] add opportunity update motorcycle card, add small fix

2024-03-22 10:10 UTC, vladplaz requested changes

2024-03-22 10:10 UTC, vladplaz commented on backend/src/api/routers/motorcycle.ts
> +
move up

2024-03-22 10:10 UTC, vladplaz commented on backend/src/api/routers/motorcycle.ts
> +        fs.access(pathToImage, fs.constants.F_OK, (err) => {
write a helper function to delete a file by path

2024-03-22 10:10 UTC, vladplaz commented on backend/src/api/routers/motorcycle.ts
> +          if (err) {
Wrap in promise (better to use fs async methods) and return 500 error if something goes wrong

2024-03-22 10:10 UTC, vladplaz commented on backend/src/api/routers/motorcycle.ts
> +      if (motorcycleData?.id) {
check for uploadImage

2024-03-22 10:10 UTC, vladplaz commented on backend/src/api/routers/motorcycle.ts
> +      if (!idMotorcycleCard) {
remove this check

2024-03-22 10:10 UTC, vladplaz commented on backend/src/api/routers/motorcycle.ts
> +      const idMotorcycleCard = req.params.id;
rename to cardId

2024-03-22 10:10 UTC, vladplaz commented on backend/src/api/routers/motorcycle.ts
> +        fs.access(pathToImage, fs.constants.F_OK, (err) => {
the same changes as for delete method

2024-03-22 10:10 UTC, vladplaz commented on backend/src/api/routers/motorcycle.ts
> +            uploadImage: {
just use uploadImage: fileMotorcycle

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +const FormCreateMotorcycleCard: React.FC<IFormCreateMotorcycleCard> = ({
rename to FormMotorcycleCard

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +  } = { ...motorcycleInfo };
use rest operator, get uploadImage and make other ...rest

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +  const preparedValues = {
use spread

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +  const [displayUpdatedImage, setDisplayUpdatedImage] = useState<boolean>(
use a prop from the outside that tells it's update form

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +      const { ['uploadImage']: _, ...preparedData } = data;
use just uploadImage

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +  requestFunction: (data: FormData) => void;
rename to onSubmit and make it promise

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +    Object.entries(data).forEach(([key, value]) => {
use a helper function to create a form data from an object

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +    const file = e.target.files;
rename to files

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +      const fakeFile = new File(['content'], 'example.jpg', {
use name from updatedUploadedImage?.filename

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +        type: 'image/jpeg',
use type from updatedUploadedImage

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +          {!preview && !displayUpdatedImage && (
move dndBlock to separate component

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/pages/CatalogMotorcycles/utils.ts
> +import axios from 'axios';
move to requests

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/pages/CreateMotorcycleCard/index.tsx
> +  const { mutate, data } = useMutation<
add error handling

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/pages/UpdateMotorcycleCard/index.tsx
> +  const { id: idFromUrl } = useParams();
keep id

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/pages/UpdateMotorcycleCard/index.tsx
> +    refetchOnWindowFocus: false,
move to context

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/pages/UpdateMotorcycleCard/index.tsx
> +    cacheTime: 0,
use invalidateQueries

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/types/CreateMotorcycleCards.ts
> +console.log('test console.log');
remove

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/request/types.ts
> +console.log('test console.log');
remove

2024-03-22 10:10 UTC, vladplaz commented on frontend/src/request/index.ts
> +console.log('test console.log');
remove

2024-03-26 14:01 UTC, ArtemVolok commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +        type: 'image/jpeg',
updatedUploadedImage has not type

2024-03-26 14:11 UTC, vladplaz commented on frontend/src/components/FormCreateMotorcycleCard/index.tsx
> +        type: 'image/jpeg',
use type from filename

2024-03-26 22:04 UTC, vladplaz approved these changes

2024-03-27 13:34 UTC, merged